#!/usr/bin/env python3
"""Static, readable guide shells; practice loads the committed question banks."""
import json, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
VERSION='20261006.study1'
FILES=['interview.html','part-time-interview.html','skype sheet.html','embassy-interview.html','listening-lab.html','jlpt-revision.html']
for filename in FILES:
    slug={'skype sheet.html':'skype-sheet'}.get(filename,filename[:-5])
    archive=ROOT/f'archive/{slug}-pre-study-20261006.html'
    if not archive.exists():
        old=(ROOT/filename).read_text()
        old=re.sub(r'</head>', '<meta name="robots" content="noindex,follow"><base href="/">\n</head>',old,count=1,flags=re.I)
        archive.write_text(old)
def svg(paths):return '<svg viewBox="0 0 24 24" aria-hidden="true">'+paths+'</svg>'
ICONS=[svg('<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>'),svg('<path d="M5 3h10l4 4v14H5zM15 3v5h4M8 12h8M8 16h6"/>'),svg('<rect x="4" y="7" width="16" height="13" rx="3"/><path d="M12 3v4M8 12v2M16 12v2M8 17h8"/>'),svg('<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2M8 11l2 2 5-5M8 17h8"/>'),svg('<circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/>')]
def shell(title,description,canonical,body,mode='',track='',script=''):
    dock=''.join(f'<a href="{url}">{ICONS[i]}<span>{label}</span></a>' for i,(url,label) in enumerate([('/','হোম'),('/cv-builder','CV Builder'),('/tutor-section','AI Tutor'),('/mock-test','Mock Test'),('/profile','প্রোফাইল')]))
    return f'''<!doctype html>
<html lang="bn" dir="ltr" data-language-preset="bn" data-source-language="bn"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>{title} | আপনার নিহোন</title><meta name="description" content="{description}"><meta name="theme-color" content="#071225">
<link rel="canonical" href="https://app.aponar-nihon.workers.dev/{canonical}"><link rel="icon" href="/logo.png"><link rel="manifest" href="/manifest.json">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700;800&amp;family=Noto+Sans+Bengali:wght@400;500;600;700;800&amp;family=Noto+Sans+JP:wght@400;500;700&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/css/study-workspace.css?v={VERSION}">
<link rel="stylesheet" href="/assets/css/app-menu.css?v=20260829.3"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<script defer src="/assets/js/app-menu.js?v=20260829.3"></script>
{f'<script defer src="/assets/js/study-shared.js?v={VERSION}"></script><script defer src="/assets/js/{script}?v={VERSION}"></script>' if script else ''}
</head><body class="study-page" data-study="{mode}" data-track="{track}">
<a class="study-skip" href="#mainContent">মূল লেখায় যান</a>
<header class="study-bar"><div class="study-bar-in"><a class="study-back" href="{'/interview' if mode=='interview' else '/'}" aria-label="ফিরে যান">←</a><a class="study-brand" href="/"><img src="/logo.png" alt=""><span><b>আপনার নিহোন</b><small>JAPANESE LEARNING HUB</small></span></a><a class="study-bar-link" href="/listening-lab">Listening</a><a class="study-bar-link" href="/interview">Interview</a><a class="study-bar-link" href="/jlpt-revision#revision">Revision</a><button class="study-back study-menu-button" type="button" data-app-menu-open aria-label="সব সেকশনের মেনু" aria-expanded="false">☰</button></div></header>
<main class="study-wrap" id="mainContent">{body}<footer class="study-footer">আপনার নিহোন · সহজ জাপানি, ফুরিগানা ও বাংলা দিয়ে প্রতিদিন অনুশীলন।</footer></main>
<nav class="study-dock" aria-label="মূল নেভিগেশন">{dock}</nav><div id="studyToast" class="study-toast" role="status" hidden></div>
<noscript><p class="study-wrap">প্রশ্নব্যাংক ও অনুশীলন চালু করতে ব্রাউজারের JavaScript চালু করুন। উপরের প্রস্তুতির গাইড পড়তে পারবেন।</p></noscript>
</body></html>'''
def panel(title,content,id=''):return f'<section class="study-panel"{f" id={chr(34)}{id}{chr(34)}" if id else ""}><h2>{title}</h2>{content}</section>'
def step(number,title,items):return f'<article class="guide-step"><h3><span class="step-number">{number}</span>{title}</h3><ul>'+''.join(f'<li>{item}</li>' for item in items)+'</ul></article>'
def guides(track):
    if track=='parttime':
        steps=[
          ('আবেদনের আগে ঠিক করুন',['ক্লাস, যাতায়াত ও বিশ্রামের সময় বাদ দিয়ে কোন দিন কতক্ষণ কাজ পারবেন লিখুন।','দোকানের কাজ, বেতন, জায়গা ও প্রশিক্ষণের বিবরণ পড়ুন। নিজের কাজের অনুমতি ও মেয়াদ দেখুন।','এক পাতার CV-তে আসল শিক্ষা, অভিজ্ঞতা ও যোগাযোগের তথ্য দিন। নতুন হলে সৎভাবে শেখার আগ্রহ দেখান।']),
          ('ফোন বা অনলাইনে আবেদন',['পরিচয় দিয়ে বলুন কোন বিজ্ঞাপনের জন্য যোগাযোগ করছেন। দায়িত্বপ্রাপ্ত ব্যক্তির সঙ্গে কথা বলতে চান।','সাক্ষাৎকারের দিন, সময়, ঠিকানা, নাম ও কী আনতে হবে নিশ্চিত করে লিখুন।','ব্যস্ত দোকানে দীর্ঘ ফোন না করে কথা বলার সুবিধা আছে কি না আগে জিজ্ঞেস করুন।']),
          ('সাক্ষাৎকারের দিন',['পরিষ্কার পরিপাটি পোশাক, CV, কলম ও চাইলে পরিচয়/কাজের অনুমতির নথি নিন। দোকানের নির্দেশ মেনে চলুন।','সাধারণত ৫–১০ মিনিট আগে পৌঁছে পরিচয় দিন। দেরি হলে আগে ফোন করে সম্ভাব্য সময় জানান।','বসতে বলা হলে বসুন। ফোন সাইলেন্ট রাখুন। প্রশ্ন শেষ পর্যন্ত শুনুন।']),
          ('মূল উত্তর চার ভাগে বলুন',['পরিচয়: নাম → বর্তমান স্কুল/কাজ। কারণ: এই কাজের সঙ্গে মেলে এমন আসল আগ্রহ।','শিফট: কোন দিন → কখন থেকে কখন → কবে শুরু। অভিজ্ঞতা: কী পারেন → কী শিখতে চান।','না বুঝলে আবার জিজ্ঞেস করুন। দীর্ঘ কঠিন উত্তর মুখস্থ করার চেয়ে ছোট সঠিক উত্তর দিন।']),
          ('কাজের ধরন অনুযায়ী প্রস্তুতি',['কনভিনি: ক্যাশ কাউন্টার, পণ্য সাজানো, মেয়াদ, পরিষ্কার ও গ্রাহকসেবা।','রেস্তোরাঁ: সার্ভিস, রান্নাঘর, অর্ডার, অ্যালার্জির তথ্য ও স্বাস্থ্যবিধি।','দোকানের পদ্ধতি শিখে কাজ করুন। টাকা, ফেরত, অ্যালার্জি বা নিরাপত্তা নিয়ে আন্দাজ করবেন না।']),
          ('নিয়োগ হলে শর্ত মিলিয়ে নিন',['ঘণ্টাপ্রতি বেতন, প্রশিক্ষণের বেতন, বেতন দেওয়ার দিন, যাতায়াত খরচ, কাজ ও সময় লিখিতভাবে পড়ুন।','প্রথম দিনের সময়, দায়িত্বপ্রাপ্ত ব্যক্তি, পোশাক ও সঙ্গে কী আনবেন নিশ্চিত করুন।','নিজের অনুমতির সীমার মধ্যে সব চাকরির মোট সময় মিলিয়ে শিফট নিন। পড়াশোনার সময় রাখুন।'])]
        note='শিক্ষার্থী হলে প্রযোজ্য কাজের অনুমতি প্রয়োজন। সাধারণ সময়ে সব চাকরি মিলিয়ে সপ্তাহে ২৮ ঘণ্টার সীমা; স্কুলের আনুষ্ঠানিক দীর্ঘ ছুটিতে সাধারণ নিয়ম দিনে ৮ ঘণ্টা। আপনার অনুমতির শর্ত ও নিষিদ্ধ কাজের ধরন অফিসিয়াল উৎসে মিলিয়ে নিন।'
        source='<a href="https://www.studyinjapan.go.jp/en/work-in-japan/part-time-jobs/" target="_blank" rel="noopener">Study in Japan · পার্ট-টাইমের অফিসিয়াল তথ্য ↗</a>'
        checklist=['সত্যি তথ্যসহ CV ও নাম','বাস্তব শিফট ও শুরু করার দিন','যাতায়াত ও শেষ ট্রেন','কাজের অনুমতি ও মেয়াদ','দোকানের কাজ সম্পর্কে ধারণা','নিজে জিজ্ঞেস করার ২টি প্রশ্ন']
    elif track=='school':
        steps=[
          ('স্কুল ও নিজের পরিকল্পনা জানুন',['স্কুলের নাম, শহর, কোর্স, intake, মেয়াদ ও ফি অফিসিয়াল তথ্য থেকে লিখুন।','কেন এই স্কুল, কী শিখবেন এবং পরের লক্ষ্য—তিনটির মধ্যে সম্পর্ক পরিষ্কার করুন।','শিক্ষা ও কাজের সময়রেখা, জাপানি শেখার সময় এবং পরীক্ষার ফল মিলিয়ে নিন।']),
          ('কলের আগে প্রস্তুতি',['স্কুলের পাঠানো সময় কোন দেশের সময় তা দেখুন। লিংক, কলের অ্যাপ ও যোগাযোগের ঠিকানা নিশ্চিত করুন।','শান্ত ঘর, আলো, ক্যামেরা, মাইক ও ইন্টারনেট পরীক্ষা করুন। ব্যাকআপ সংযোগ রাখুন।','পরিচয়পত্র, আবেদন ও প্রয়োজনীয় কাগজ হাতের কাছে রাখুন। স্কুলের অনুমোদিত নিয়মে অংশ নিন।']),
          ('উত্তর সাজানোর সহজ নিয়ম',['পরিচয় ৪৫–৬০ সেকেন্ডে। কারণ বলতে নিজের লক্ষ্য ও স্কুলের একটি নির্দিষ্ট বৈশিষ্ট্য বলুন।','পড়ার পরিকল্পনায় ক্লাস, নিজের পড়া, ভাষার লক্ষ্য ও পরের ধাপ রাখুন।','প্রতিটি নমুনার 【ঘর】 নিজের তথ্য দিয়ে পূরণ করুন। মুখে বলে অনুশীলন করুন।']),
          ('অর্থায়ন ও জীবন',['স্পনসর কে, সম্পর্ক, পেশা, ফি ও মাসিক বাজেট নিজের কাগজ অনুযায়ী জানুন।','বাসা ও যাতায়াতের পরিকল্পনা করুন। শুধু পার্ট-টাইম আয় দিয়ে সব খরচ চলবে ধরে নেবেন না।','অসুস্থতা, পড়ায় সমস্যা বা সংযোগ বিচ্ছিন্ন হলে কাকে জানাবেন ঠিক করুন।']),
          ('কলের সময়',['প্রশ্ন শুনে ছোট উত্তর দিন। ক্যামেরার দিকে তাকান; অন্য কারও লেখা পড়ে অপ্রাসঙ্গিক উত্তর নয়।','শব্দ কেটে গেলে বলুন সংযোগের সমস্যা। ভাষা না বুঝলে সহজ করে আবার বলতে বলুন।','ভুল তথ্য বলে ফেললে সঙ্গে সঙ্গে সংশোধন করুন। উত্তর বানিয়ে ফাঁক ভরাট করবেন না।']),
          ('শেষ ও পরের ধাপ',['পড়ার প্রস্তুতি বা স্কুলের সহায়তা নিয়ে প্রাসঙ্গিক প্রশ্ন করুন।','ধন্যবাদ দিয়ে শেষ করুন। অতিরিক্ত নথি বা পরের নির্দেশ লিখে রাখুন।','এখানকার প্রশ্ন অনুশীলনের নমুনা; আপনার স্কুলের সাক্ষাৎকারে প্রশ্ন ও ভাষা আলাদা হতে পারে।'])]
        note='School / Skype নামের এই গাইড অনলাইন বা সরাসরি স্কুলের সাক্ষাৎকার—দুটোর জন্য। স্কুল যে কলের মাধ্যম পাঠাবে সেটিই ব্যবহার করুন। নমুনার ব্যক্তিগত তথ্য নিজের তথ্য দিয়ে বদলান।'
        source='<a href="https://www.studyinjapan.go.jp/en/" target="_blank" rel="noopener">Study in Japan · পড়াশোনার অফিসিয়াল তথ্য ↗</a>'
        checklist=['স্কুল, কোর্স, intake ও ফি','পড়ার কারণ ও পরের লক্ষ্য','আসল শিক্ষা ও কাজের সময়রেখা','জাপানি শেখা ও পরীক্ষার তথ্য','স্পনসর ও বাস্তব বাজেট','সময় অঞ্চল, ক্যামেরা ও ইন্টারনেট']
    else:
        steps=[
          ('আবেদনের তথ্য নিজে বুঝুন',['এই গাইড মূলত শিক্ষার্থী আবেদনের ভাষা অনুশীলন। আপনার ভিসার ধরন অনুযায়ী আসল উদ্দেশ্য বলুন।','নাম, জন্মতারিখ, স্কুল, কোর্স, intake, মেয়াদ ও পরিকল্পনা নিজের আবেদন দেখে লিখুন।','যে কাগজ জমা দিয়েছেন তা বুঝে রাখুন; অন্য কেউ পূরণ করলেও তথ্যের মিল পরীক্ষা করুন।']),
          ('পড়ার উদ্দেশ্য পরিষ্কার করুন',['কেন জাপান → কেন এই স্কুল → কী পড়বেন → পরে কী করবেন। উত্তরগুলো একই বাস্তব পরিকল্পনা বোঝাবে।','আগের পড়া বা কাজের সঙ্গে সম্পর্ক থাকলে বলুন; বিষয় বদলালে আসল কারণ দিন।','বিরতি থাকলে কী করেছেন ও কেন করেছেন সত্যি সময়রেখায় বলুন।']),
          ('স্পনসর ও টাকা জানুন',['স্পনসরের নাম, সম্পর্ক, কাজ, আয় এবং সহায়তার কারণ নিজের প্রমাণ অনুযায়ী জানুন।','ফি, মাসিক বাজেট, টাকা দেওয়ার অবস্থা, ব্যাংক সনদের তারিখ ও মুদ্রা আলাদা করে লিখুন।','বড় জমা বা অর্থের উৎসের ব্যাখ্যা নিজের লেনদেনের সত্যি কাগজ দিয়ে প্রস্তুত করুন।']),
          ('নথির অমিল আগে দেখুন',['নামের বানান, তারিখ, অঙ্ক ও সময়রেখায় অমিল থাকলে আগে কারণ ও প্রয়োজনীয় সংশোধন জানুন।','উত্তরে ভুল হলে সঠিক তথ্য বলে সংশোধন করুন। অজানা অঙ্ক অনুমান না করে দেখে বলার অনুমতি চান।','অতিরিক্ত নথি চাইলে কী লাগবে এবং কীভাবে জমা দেবেন নিশ্চিত করুন।']),
          ('সাক্ষাৎকারে সংক্ষিপ্ত উত্তর',['প্রশ্ন শুনে প্রথমে সরাসরি উত্তর দিন। বিস্তারিত চাইলে নিজের তথ্য দিয়ে উদাহরণ দিন।','জাপানি না বুঝলে পুনরায় ব্যাখ্যা চাইতে পারেন। সাক্ষাৎকারের ভাষা ও ধরন কর্তৃপক্ষ ঠিক করবে।','মুখস্থ তৈরি গল্প নয়—নিজের পরিকল্পনা ও কাগজের সঙ্গে মিলিয়ে উত্তর দিন।']),
          ('নিয়ম ও পরবর্তী নির্দেশ',['থাকার মেয়াদ, অনুমোদিত কাজ ও পড়াশোনার শর্ত সম্পর্কে অফিসিয়াল তথ্য দেখুন।','জাপানে থাকা, পড়া শেষের পরিকল্পনা ও আগের ভ্রমণের তথ্য সত্যি বলুন।','আবেদন জমা, নথি ও সাক্ষাৎকারের বর্তমান নির্দেশ Embassy/VFS-এর অফিসিয়াল লিংকে দেখুন।'])]
        note='এগুলো অনুশীলনের নমুনা প্রশ্ন ও উত্তর; কোনো দূতাবাসের নির্ধারিত প্রশ্নতালিকা বা ভিসা পাওয়ার নিশ্চয়তা নয়। ব্যক্তিগত তথ্য, অর্থের অঙ্ক ও পরিকল্পনা নিজের সত্যি নথি অনুযায়ী পূরণ করুন।'
        source='<a href="https://www.bd.emb-japan.go.jp/itpr_en/visa.html" target="_blank" rel="noopener">বাংলাদেশে জাপান দূতাবাস · ভিসা তথ্য ↗</a><a href="https://visa.vfsglobal.com/bgd/en/jpn" target="_blank" rel="noopener">VFS Japan Bangladesh ↗</a>'
        checklist=['আবেদনের উদ্দেশ্য ও স্ট্যাটাস','স্কুল, intake, কোর্স ও মেয়াদ','শিক্ষা, কাজ ও বিরতির সময়রেখা','স্পনসর, আয় ও অর্থের উৎস','ফি, বাজেট ও ব্যাংক সনদের তথ্য','নথির বানান, তারিখ ও অঙ্কের মিল']
    html='<div class="guide-grid">'+''.join(step(i+1,t,items) for i,(t,items) in enumerate(steps))+'</div>'
    html+=f'<p class="guide-note">{note}</p><div class="study-source">{source}</div><details><summary>সাক্ষাৎকারের আগে নিজের চেকলিস্ট</summary><ul>'+''.join(f'<li>{c}</li>' for c in checklist)+'</ul></details>'
    return html
counts={t:len(json.loads((ROOT/f'assets/data/study/interview-{t}.json').read_text())['questions']) for t in ['parttime','school','embassy']}
tracks=[('parttime','Part-time Job Interview','পার্ট-টাইম কাজের প্রস্তুতি','part-time-interview.html','দোকানের ফোন থেকে প্রথম দিন—কনভিনি, রেস্তোরাঁ, শিফট, অনুমতি ও কাজের বাস্তব পরিস্থিতি।',''),('school','School / Skype Interview','স্কুল ও অনলাইন সাক্ষাৎকার','skype sheet.html','পরিচয়, কেন জাপান, পড়ার পরিকল্পনা, স্পনসর ও অনলাইন কল—সব এক জায়গায়।','blue'),('embassy','Embassy Interview','ভিসার সাক্ষাৎকার অনুশীলন','embassy-interview.html','নিজের আবেদন বুঝে উদ্দেশ্য, স্কুল, স্পনসর, বাজেট ও নথির বিষয়ে সত্যি তথ্য দিয়ে উত্তর।','pink')]
for track,title,bn,file,lead,color in tracks:
    body=f'<section class="study-hero"><span class="eyebrow">INTERVIEW WORKSPACE · {bn}</span><h1>{title}</h1><p class="study-lead">{lead}</p><div class="pill-row"><span class="study-pill">{counts[track]}টি পূর্ণ প্রশ্নোত্তর</span><span class="study-pill">ফুরিগানা</span><span class="study-pill">বাংলা উচ্চারণ ও অর্থ</span></div></section>'
    body+='<nav class="study-tabs" aria-label="এই গাইড"><a class="study-btn" href="#guide">১. প্রস্তুতি পড়ুন</a><a class="study-btn" href="#questions">২. প্রশ্নোত্তর পড়ুন</a><a class="study-btn" href="#practice">৩. নিজে উত্তর দিন</a></nav>'
    body+=panel('আগে পুরো প্রক্রিয়াটি বুঝুন',guides(track),'guide')
    body+=panel('প্রশ্ন ও নমুনা উত্তর','<p class="study-muted">প্রশ্নের বাংলা অর্থ দেখুন, জাপানি উত্তর পড়ুন। 【ঘরগুলো】 নিজের তথ্য দিয়ে পূরণ করুন। বাংলা হরফের উচ্চারণ পড়ার সহায়তা; জাপানি উচ্চারণ শুনে মিলিয়ে অনুশীলন করুন।</p><div id="interviewStats" class="study-stats"></div><div class="study-controls"><div class="study-control search"><label for="interviewSearch">প্রশ্ন, উত্তর বা বিষয় খুঁজুন</label><input id="interviewSearch" type="search" placeholder="শিফট, sponsor, 学校…"></div><div class="study-control"><label for="interviewView">যা দেখতে চান</label><select id="interviewView"><option value="all">সব প্রশ্ন</option><option value="saved">রাখা প্রশ্ন</option><option value="unread">এখনো পড়িনি</option></select></div></div><div id="interviewTopics" class="study-chips" aria-label="প্রশ্নের বিষয়"></div><p id="interviewCount" class="study-small" aria-live="polite"></p><div id="interviewList"><p class="study-empty">প্রশ্নোত্তর লোড হচ্ছে…</p></div><button class="study-btn" type="button" id="interviewMore" hidden>আরও প্রশ্ন দেখুন</button>','questions')
    body+=panel('নিজে বলে ও লিখে অনুশীলন করুন','<p class="study-muted">প্রশ্ন দেখে আগে নিজের উত্তর বলুন। চাইলে লিখে রাখুন, তারপর নমুনা উত্তরের সঙ্গে মিলিয়ে দেখুন। লেখা এই ব্রাউজারে থাকবে।</p><div id="interviewPractice"><p class="study-empty">অনুশীলন লোড হচ্ছে…</p></div>','practice')
    legacy={'parttime':'/archive/part-time-interview-pre-study-20261006.html','school':'/archive/skype-sheet-legacy.html','embassy':'/archive/embassy-interview-legacy.html'}[track]
    body+=f'<p class="study-small"><a href="{legacy}">আগের রেফারেন্স পেজ পড়ুন ↗</a> · <a href="/interview">সব ইন্টারভিউ গাইড</a></p>'
    (ROOT/file).write_text(shell(title,f'{counts[track]}টি প্রশ্ন ও সহজ নমুনা উত্তর—জাপানি ফুরিগানা, বাংলা উচ্চারণ, প্রশ্ন ও উত্তরের বাংলা অর্থ।',file[:-5].replace(' ','%20'),body,'interview',track,'interview-workspace.js'))
cards=''.join(f'<a class="study-card {color}" data-track="{t}" href="/{file[:-5].replace(" ","%20")}"><span class="card-icon" aria-hidden="true">{icon}</span><span class="eyebrow">{bn}</span><h2>{title}</h2><p>{lead}</p><div class="pill-row"><span class="study-pill">{counts[t]} প্রশ্নোত্তর</span><span class="study-pill">ফুরিগানা + বাংলা</span></div><span class="card-link">পুরো গাইড খুলুন →</span></a>' for (t,title,bn,file,lead,color),icon in zip(tracks,['▣','▷','▤']))
hub=f'<div data-learning-hub="interview"><section class="study-hero lh-hero"><span class="eyebrow">INTERVIEW HUB</span><h1>প্রশ্ন বুঝুন। নিজের উত্তর বলুন।</h1><p class="study-lead">চাকরি, স্কুল ও ভিসার প্রস্তুতি। প্রতিটি গাইডে ধাপে ধাপে করণীয়, সহজ জাপানি, ফুরিগানা, বাংলা উচ্চারণ এবং প্রশ্ন–উত্তরের বাংলা অর্থ।</p><div class="pill-row"><span class="study-pill">{sum(counts.values())} নতুন পূর্ণ প্রশ্নোত্তর</span><span class="study-pill">পড়া + অনুশীলন</span><span class="study-pill" data-progress-value>পড়েছি ০ / {sum(counts.values())}</span></div></section><div class="study-grid">{cards}</div></div>'
hub+=panel('কীভাবে ব্যবহার করবেন','<ol><li>নিজের সাক্ষাৎকারের গাইড খুলে আগে প্রস্তুতির ধাপগুলো পড়ুন।</li><li>বিষয় ধরে প্রশ্নোত্তর পড়ুন। নমুনার 【ঘরগুলো】 নিজের সত্যি তথ্য দিয়ে পূরণ করুন।</li><li>“নিজে উত্তর দিন” অংশে উত্তর বলুন বা লিখুন। কঠিন প্রশ্নগুলো রেখে আবার অনুশীলন করুন।</li></ol><div class="button-row"><a class="study-btn" href="/ssw-interview">SSW Job Interview →</a><a class="study-btn quiet" href="/tutor-section?mode=interview">AI Tutor-এ অনুশীলন →</a></div>')
(ROOT/'interview.html').write_text(shell('জাপানি ইন্টারভিউ প্রস্তুতি','Part-time, School/Skype ও Embassy—পূর্ণ প্রশ্নোত্তর, ফুরিগানা, বাংলা উচ্চারণ ও অর্থ।','interview',hub,'interview-hub','','interview-hub-workspace.js'))
listening='''<section class="study-hero"><span class="eyebrow">LISTENING HUB · N5 / N4 / N3</span><h1>শুনুন। উত্তর দিন। বুঝে শিখুন।</h1><p class="study-lead">৮০০টি রেকর্ড করা অনুশীলন। আপনার দেওয়া JapaneseTest4You উৎসের ২০৮টি প্রশ্ন এবং আপনার নিহোনের ৫৯২টি নিজস্ব অডিও প্রশ্ন। প্রতিটিতে সঠিক উত্তর ও বাংলায় কারণ আছে।</p><div class="pill-row"><span class="study-pill">N5 · 240</span><span class="study-pill">N4 · 280</span><span class="study-pill">N3 · 280</span><span class="study-pill">অডিও + ফুরিগানা</span></div></section>
<div class="study-controls"><div class="study-control"><label for="listeningLevel">আপনার লেভেল</label><select id="listeningLevel"><option value="n5">JLPT N5</option><option value="n4">JLPT N4</option><option value="n3">JLPT N3</option></select></div><div class="study-control"><label for="listeningSource">প্রশ্নের উৎস</label><select id="listeningSource"><option value="all">সব উৎস</option><option value="source">JapaneseTest4You</option><option value="original">আপনার নিহোন · নিজস্ব</option></select></div><div class="study-control"><label for="listeningMode">অনুশীলন</label><select id="listeningMode"><option value="all">সব অনুশীলন</option><option value="new">এখনো উত্তর দিইনি</option><option value="weak">ভুলগুলো আবার</option><option value="saved">রাখা প্রশ্ন</option></select></div></div><div id="listeningStats" class="study-stats"></div>
<div class="study-layout"><section id="listeningExercise" class="study-panel" aria-label="অডিও প্রশ্ন"><p class="study-empty">লিসেনিং লোড হচ্ছে…</p></section><aside class="study-sidebar study-panel"><h2>পাঠের তালিকা</h2><div class="study-control"><label for="listeningSearch">প্রশ্ন খুঁজুন</label><input type="search" id="listeningSearch" placeholder="অডিওর বিষয় বা নম্বর…"></div><p class="study-small" id="listeningCount" aria-live="polite"></p><div id="listeningLessons" class="lesson-list"></div><button class="study-btn" id="listeningMore" hidden>আরও পাঠ দেখুন</button></aside></div>
<section class="study-panel"><h2>শুনে শেখার ছোট রুটিন</h2><ol><li>ছবি বা বিকল্প দেখে কী তথ্য খুঁজবেন বুঝুন। একবার স্বাভাবিক গতিতে শুনুন।</li><li>উত্তর বেছে “উত্তর যাচাই” করুন। ভুল হলে কোন সিদ্ধান্ত, সময় বা পরিবর্তন মিস হয়েছে দেখুন।</li><li>ফুরিগানাসহ স্ক্রিপ্ট খুলে অডিও আবার শুনুন। নিজের মুখে একটি ছোট অংশ বলুন।</li><li>ভুল প্রশ্ন “ভুলগুলো আবার” তালিকায় থাকবে। পরে ঠিক করলে তালিকা থেকে সরবে।</li></ol><p class="study-small">JapaneseTest4You প্রশ্নে মূল রেকর্ডিং ও উৎসের লিংক আছে। নিজস্ব প্রশ্নে রেকর্ড করা জাপানি যন্ত্রকণ্ঠ (VOICEVOX) ব্যবহার করা হয়েছে। নিজস্ব প্রশ্নে সম্পূর্ণ বাংলা স্ক্রিপ্ট; উৎসের প্রশ্নে বাংলা উত্তর ও ব্যাখ্যা আছে। একই প্রশ্ন Mock Test-এও ব্যবহার করা হয়েছে।</p><div class="button-row"><a class="study-btn" href="/jlpt-revision#revision">মিশ্র Revision →</a><a class="study-btn quiet" href="/archive/listening-lab-pre-study-20261006">আগের ৬০টি সহায়ক পাঠ →</a></div></section>'''
(ROOT/'listening-lab.html').write_text(shell('Listening Hub · 800 অডিও অনুশীলন','N5 N4 N3-এর ৮০০টি রেকর্ড করা লিসেনিং—JapaneseTest4You উৎস, নিজস্ব অনুশীলন, বাংলা ব্যাখ্যা, ফুরিগানা ও ভুল রিভিউ।','listening-lab',listening,'listening','','listening-workspace.js'))
revision='''<section class="study-hero"><span class="eyebrow">FULL REVISION · N5 / N4 / N3</span><h1>আজ পড়া মনে আছে?</h1><p class="study-lead">ছোট প্রশ্নের সেশন দিয়ে ঝালাই করুন। ব্যাকরণ, শব্দ, কানজি, রিডিং ও লিসেনিং—২,৫৪০টি যাচাই করা প্রশ্ন। উত্তর দিলে বাংলা ব্যাখ্যা দেখুন, ভুলগুলো পরে আবার করুন।</p><div class="pill-row"><span class="study-pill">N5 · 670</span><span class="study-pill">N4 · 850</span><span class="study-pill">N3 · 1020</span></div></section>
<nav class="study-tabs" aria-label="রিভিশনের ধরন"><a class="study-btn" href="#revision" id="revisionTab">প্রশ্ন দিয়ে Revision</a><a class="study-btn" href="#flash" id="flashTab">Kanji Flashcards</a><a class="study-btn quiet" href="/mock-test">পূর্ণ Mock Test →</a></nav>
<div class="study-controls"><div class="study-control"><label for="revisionLevel">লেভেল</label><select id="revisionLevel"><option value="n5">JLPT N5</option><option value="n4">JLPT N4</option><option value="n3">JLPT N3</option></select></div></div><div id="revisionStats" class="study-stats"></div>
<section id="revisionWorkspace" class="study-panel"><h2>আজকের অনুশীলন বাছুন</h2><p class="study-muted">আগে না করা প্রশ্নকে অগ্রাধিকার দেওয়া হবে। এই অনুশীলন ব্যাংকের প্রশ্নগুলো Mock Test-এও আছে।</p><div class="study-controls"><div class="study-control"><label for="revisionSubject">বিষয়</label><select id="revisionSubject"><option value="all">সব বিষয় মিশিয়ে</option><option value="grammar">ব্যাকরণ</option><option value="vocabulary">শব্দভান্ডার</option><option value="kanji">কানজি</option><option value="reading">রিডিং</option><option value="listening">লিসেনিং</option></select></div><div class="study-control"><label for="revisionLength">প্রশ্নের সংখ্যা</label><select id="revisionLength"><option value="10">১০টি · ছোট সেশন</option><option value="20">২০টি · বেশি অনুশীলন</option></select></div></div><div class="button-row"><button type="button" class="study-btn primary" id="revisionStart">নতুন সেশন শুরু</button><button type="button" class="study-btn teal" id="revisionWeak">ভুলগুলো আবার করি</button><button type="button" class="study-btn" id="revisionResume" hidden>আগের সেশন চালিয়ে যান</button></div><p id="revisionSetupMessage" class="study-small" role="status"></p><div id="revisionQuestion" style="margin-top:24px"><p class="study-empty">প্রশ্নব্যাংক লোড হচ্ছে…</p></div></section>
<section id="flashWorkspace" class="study-panel" hidden><h2>দেখে নয়, মনে করে বলুন</h2><p class="study-muted">কানজির অর্থ ও একটি শব্দ মনে করার চেষ্টা করুন। তারপর পেছন দেখুন। আগের Flashcard-এর অগ্রগতি রাখা হয়েছে।</p><div class="study-controls"><div class="study-control"><label for="flashFilter">কার্ডের তালিকা</label><select id="flashFilter"><option value="due">আজ রিভিউ দরকার</option><option value="all">সব কার্ড</option><option value="weak">কঠিন কার্ড</option><option value="saved">রাখা কার্ড</option></select></div></div><div id="flashCard"><p class="study-empty">কার্ড লোড হচ্ছে…</p></div></section>
<section class="study-panel"><h2>ভুল কমানোর রুটিন</h2><ol><li>প্রতিদিন একটি ছোট সেশন করুন। আন্দাজে ঠিক হলে ব্যাখ্যাটি পড়ুন।</li><li>“ভুলগুলো আবার করি” খুলে উত্তর না দেখে চেষ্টা করুন। ঠিক হলে প্রশ্নটি ভুলের তালিকা থেকে সরে যাবে।</li><li>একই বিষয়ে বারবার ভুল হলে নিচের লেভেলের পাঠে নিয়মটি পড়ুন।</li><li>সময়সীমাসহ পুরো পরীক্ষা দিতে Mock Test খুলুন। এখানে শেখার জন্য প্রশ্ন ধরে অনুশীলন।</li></ol><div id="revisionLessonLinks" class="button-row"></div></section>'''
(ROOT/'jlpt-revision.html').write_text(shell('Full Revision · বাস্তব প্রশ্ন ও ভুলের রিভিউ','N5 N4 N3-এর ২৫৪০টি প্রশ্ন, বাংলা ব্যাখ্যা, আসল অডিও, ভুল প্রশ্ন আবার করা, সেশন চালিয়ে যাওয়া এবং কানজি ফ্ল্যাশকার্ড।','jlpt-revision',revision,'revision','','revision-workspace.js'))
print('Built six study pages. Counts:',counts)
