"""Optional asset regeneration: sudachipy==0.6.11, sudachidict_core==20260723.
All example readings are shipped with the site; no reading API at runtime.
"""
import json, re, subprocess
from pathlib import Path
from sudachipy import dictionary, tokenizer
root=Path(__file__).resolve().parents[1]
extract="""const fs=require('node:fs'),vm=require('node:vm'),c={window:{}};for(const f of ['data','details','examples','teacher'])vm.runInNewContext(fs.readFileSync(`assets/js/n3-matome-${f}.js`,'utf8'),c);const w=c.window;console.log(JSON.stringify(w.N3_MATOME_RULES.flatMap(r=>[r[7],...w.N3_MATOME_DETAILS[r[0]].examples.map(x=>x[0]),...w.N3_MATOME_EXTRA_EXAMPLES[r[0]].map(x=>x[0]),w.N3_MATOME_FOCUS[r[0]]])));"""
sentences=json.loads(subprocess.check_output(['node','-e',extract],cwd=root,text=True))
engine=dictionary.Dictionary().create(); kanji=re.compile(r'[\u3400-\u9fff々〆]')
readings={}
for sentence in dict.fromkeys(sentences):
    parts=[]
    for token in engine.tokenize(sentence,tokenizer.Tokenizer.SplitMode.C):
        surface=token.surface()
        if kanji.search(surface):
            reading=''.join(chr(ord(c)-0x60) if '\u30a1'<=c<='\u30f6' else c for c in token.reading_form())
            reading={'今日':'きょう','明日':'あした','昨日':'きのう','日本':'にほん','一日':'いちにち','何時':'なんじ'}.get(surface,reading)
            assert reading and not kanji.search(reading),(sentence,surface)
            parts.append([surface,reading])
        elif parts and len(parts[-1])==1: parts[-1][0]+=surface
        else: parts.append([surface])
    assert ''.join(p[0] for p in parts)==sentence
    readings[sentence]=parts
output='// Generated by tools/build_matome_readings.py\nwindow.N3_MATOME_READINGS = {\n'+',\n'.join('  '+json.dumps(k,ensure_ascii=False)+':'+json.dumps(v,ensure_ascii=False,separators=(',',':')) for k,v in readings.items())+'\n};\n'
(root/'assets/js/n3-matome-readings.js').write_text(output,encoding='utf-8')
print(f'{len(sentences)} example/focus occurrences; {len(readings)} unique strings.')
